import json
import os
import shutil
from datetime import datetime
from pathlib import Path
from typing import Any

from maestro.orch.forest_types import ForestPlan


class RunArchive:
    """
    Handles the structured documentation and archiving of Maestro runs.
    Creates a predictable, timestamped directory structure for easy debugging and data collection.
    """

    def __init__(self, workspace_root: Path):
        self.workspace_root = workspace_root
        self.archive_root = self.workspace_root / "runs"
        self.archive_root.mkdir(parents=True, exist_ok=True)
        
        # Generate run name: YYYY-MM-DD_HH-MM-SS
        timestamp = datetime.now().strftime("%Y-%m-%d_%H-%M-%S")
        self.run_dir = self.archive_root / timestamp
        self.run_dir.mkdir(parents=True, exist_ok=True)

        self._update_latest_symlink()

    def _update_latest_symlink(self):
        """Updates the 'latest' symlink to point to the current run directory."""
        latest_link = self.archive_root / "latest"
        if latest_link.exists() or latest_link.is_symlink():
            latest_link.unlink()
        try:
            # Create a relative symlink
            os.symlink(self.run_dir.name, latest_link)
        except OSError as e:
            print(f"[!] Warning: Could not create 'latest' symlink: {e}")

    def log_request(self, request_text: str):
        """Saves the initial user request."""
        (self.run_dir / "request.txt").write_text(request_text, encoding="utf-8")

    def log_plan(self, plan: ForestPlan):
        """Saves the ForestPlan generated by Raven."""
        import dataclasses
        plan_dict = dataclasses.asdict(plan)
        with open(self.run_dir / "forest_plan.json", "w", encoding="utf-8") as f:
            json.dump(plan_dict, f, indent=2)

    def log_interactions(self, interactions: list[dict[str, Any]]):
        """Saves the complete interaction history (Luna + Trees) for the run."""
        with open(self.run_dir / "interaction_log.json", "w", encoding="utf-8") as f:
            json.dump(interactions, f, indent=2)

    def save_diff(self, task_id: str, diff_content: str):
        """Saves successful diffs for specific tasks."""
        diffs_dir = self.run_dir / "diffs"
        diffs_dir.mkdir(exist_ok=True)
        (diffs_dir / f"{task_id}.patch").write_text(diff_content, encoding="utf-8")

    def append_validation_log(self, log_output: str):
        """Appends validation results (pytest, linters) to the run's validation log."""
        with open(self.run_dir / "validation.log", "a", encoding="utf-8") as f:
            f.write(log_output + "\n")
