from __future__ import annotations

import subprocess
from dataclasses import dataclass, field
from typing import List, Optional

@dataclass
class TreeTask:
    id: str
    task: str           # Formerly description
    files: str          # Formerly target_files
    symbols: str        # Specific functions/classes to touch
    intent: str         # Feature | Refactor | Bugfix | Docs | Test
    complexity: int = 2 # 1=Trivial, 2=Normal, 3=Complex, 4=Expert
    tools: List[str] = field(default_factory=list) # e.g. ["cxm"]
    potential_pitfalls: Optional[str] = None
    constraints: Optional[str] = None

@dataclass
class ForestPlan:
    goal: str
    tasks: List[TreeTask]

class CXMBridge:
    """
    Bridge to the external 'cxm' CLI tool for context harvesting.
    """
    def __init__(self, workspace_path: str):
        self.workspace_path = workspace_path

    def harvest(self, query: str, intent: str) -> str:
        """
        Calls 'cxm harvest' with a refined query generated by Luna.
        """
        try:
            # We treat the refined query as the primary search term
            cmd = [
                "cxm", "harvest", 
                query, 
                "--intent", intent, 
                "--format", "xml"
            ]
            print(f"[CXM] Harvesting context with refined query: {query[:100]}...")
            
            result = subprocess.run(
                cmd,
                cwd=self.workspace_path,
                capture_output=True,
                text=True,
                timeout=60
            )
            
            if result.returncode == 0:
                return result.stdout.strip()
            else:
                print(f"[CXM] Warning: Harvest failed ({result.returncode}). Stderr: {result.stderr}")
                return f"<!-- CXM Harvest Failed: {result.stderr} -->"
        except FileNotFoundError:
            print("[CXM] 'cxm' executable not found. Ensure it is installed and in PATH.")
            return "<!-- CXM tool not available. No context harvested. -->"
        except subprocess.TimeoutExpired:
            print("[CXM] Timeout while harvesting context.")
            return "<!-- CXM Harvest Timeout -->"
