from __future__ import annotations

import re
import logging
from typing import List, Optional
from maestro.orch.forest_types import ForestPlan, TreeTask

logger = logging.getLogger("maestro.orch.plan_filters")

# --- FIX 1: Markdown Fence Cleaner & Diff Extractor ---

def clean_diff_output(raw_output: str) -> Optional[str]:
    """
    Strips Markdown fences and extracts a unified diff from the raw tree output.
    
    Args:
        raw_output: The raw string produced by the Tree model.
        
    Returns:
        The cleaned diff string starting with '--- a/' or None if no diff found.
    """
    # Remove markdown fences: ```[lang]\n...\n```
    # Also handle cases where fences are not properly closed or on separate lines
    # We use multiline flag to handle indented fences if necessary
    cleaned = re.sub(r"^\s*```[a-zA-Z]*\s*$", "", raw_output, flags=re.MULTILINE)
    cleaned = cleaned.replace("```", "").strip()

    # Search for the unified diff pattern: --- a/ followed by +++ b/ and @@
    # We allow some leading whitespace before --- a/ for robustness
    diff_pattern = r"(\s*--- a/.*?\n\s*\+\+\+ b/.*?\n\s*@@.*)"
    match = re.search(diff_pattern, cleaned, re.DOTALL)
    
    if match:
        extracted = match.group(1).strip()
        # Clean up any leading whitespace from each line if it was indented
        # Actually, diff parsers might be sensitive to this, but usually they want the header at start of line
        lines = extracted.splitlines()
        if lines and lines[0].strip().startswith("--- a/"):
            # Surgically re-align to start of line
            realigned = []
            for line in lines:
                realigned.append(line.lstrip() if line.lstrip().startswith(('---', '+++', '@@', '+', '-', ' ')) else line)
            return "\n".join(realigned)
        return extracted
    
    # Fallback: check if the cleaned string itself starts with a diff header (ignoring whitespace)
    if cleaned.lstrip().startswith("--- a/"):
        return cleaned.lstrip()
        
    return None

# --- FIX 2: Raven Task Filter ---

ACTIONABLE_KEYWORDS = [
    "add", "create", "implement", "modify", "change", "update", "fix", "refactor", 
    "integrate", "instantiate", "import", "write", "extend", "replace", "log", 
    "insert", "remove", "delete", "rename", "move", "wrap", "extract", "merge", 
    "split", "convert", "migrate"
]

READ_ONLY_KEYWORDS = [
    "identify", "understand", "locate", "find", "analyze", "review", "read", 
    "examine", "check", "inspect", "explore", "study", "document", "verify", 
    "ensure", "investigate", "determine", "assess", "evaluate", "observe", 
    "note", "learn", "familiarize"
]

def filter_raven_plan(plan: ForestPlan) -> ForestPlan:
    """
    Filters out non-actionable (read-only) tasks from the ForestPlan.
    
    Args:
        plan: The original ForestPlan generated by Raven.
        
    Returns:
        A new ForestPlan with only actionable tasks.
    """
    filtered_tasks = []
    
    for task in plan.tasks:
        combined = (task.intent + " " + task.task).lower()
        
        # Actionable check using word boundaries
        is_actionable = any(re.search(rf"\b{re.escape(kw)}\b", combined) for kw in ACTIONABLE_KEYWORDS)
        
        # Read-only check using word boundaries
        is_read_only = any(re.search(rf"\b{re.escape(kw)}\b", combined) for kw in READ_ONLY_KEYWORDS)
        
        # Special case for Test tasks
        is_test = re.search(rf"\btest\b", combined)
        if is_test:
            # Actionable test if it involves writing/creating/adding
            is_actionable_test = any(re.search(rf"\b{re.escape(kw)}\b", combined) for kw in ["write", "create", "add"])
            if is_actionable_test:
                filtered_tasks.append(task)
                continue
            else:
                # Pure "test" or "verify" without "write" is considered read-only
                logger.info(f"Filtering read-only test task: {task.id} - {task.task}")
                continue

        # Logic: If it matches read-only keywords AND doesn't match actionable keywords, filter it.
        if is_read_only and not is_actionable:
            logger.info(f"Filtering read-only task: {task.id} - {task.task}")
            continue
            
        filtered_tasks.append(task)
        
    if not filtered_tasks:
        logger.warning("No actionable tasks remaining after filtering. Roadmap may need manual review.")
        
    return ForestPlan(goal=plan.goal, tasks=filtered_tasks)

# --- FIX 3: Task Merger ---

def merge_similar_tasks(plan: ForestPlan) -> ForestPlan:
    """
    Merges tasks that target the same files and symbols.
    
    Args:
        plan: The ForestPlan (usually after filtering).
        
    Returns:
        A ForestPlan with merged tasks.
    """
    groups = {}
    for task in plan.tasks:
        key = (task.files, task.symbols)
        if key not in groups:
            groups[key] = []
        groups[key].append(task)
        
    merged_tasks = []
    for (files, symbols), task_list in groups.items():
        if len(task_list) == 1:
            merged_tasks.append(task_list[0])
            continue
            
        # Merge multiple tasks
        first = task_list[0]
        new_task_str = " AND ".join(t.task for t in task_list)
        new_intent_str = " + ".join(t.intent for t in task_list)
        max_complexity = max(t.complexity for t in task_list)
        
        merged_task = TreeTask(
            id=first.id,
            task=new_task_str,
            files=files,
            symbols=symbols,
            intent=new_intent_str,
            complexity=max_complexity,
            tools=list(set(tool for t in task_list for tool in t.tools)),
            potential_pitfalls=" | ".join(filter(None, [t.potential_pitfalls for t in task_list])),
            constraints=" | ".join(filter(None, [t.constraints for t in task_list]))
        )
        merged_tasks.append(merged_task)
        logger.info(f"Merged {len(task_list)} tasks on file {files} and symbols {symbols}")
        
    return ForestPlan(goal=plan.goal, tasks=merged_tasks)

# --- FIX 4: Error Compaction for Missing Patch ---

def contains_diff(output: str) -> bool:
    """Checks if the output contains a unified diff or FILE block."""
    return "--- a/" in output or "+++ b/" in output or "FILE:" in output

def compact_no_patch_error(task: TreeTask, raw_output: str) -> str:
    """
    Generates a specific error message if the Tree failed to produce a code change.
    
    Args:
        task: The current TreeTask.
        raw_output: The raw output from the Tree model.
        
    Returns:
        A surgical fix hint focusing on the missing format.
    """
    if not contains_diff(raw_output):
        return (
            f"Your output contained no code change. Produce a unified diff for {task.files}. "
            f"Modify: {task.symbols}. Intent: {task.intent}"
        )
    
    # If it DOES contain a diff but failed application, we should use standard compaction
    # (But this function is specifically for the 'no patch' case)
    return f"Patch application failed for {task.files}. Ensure unified diff format is correct."
